# This is a basic workflow to help you get started with Actions

name: Build PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build PDF using the basic commands
        uses: docker://feastingmonk/sofp-builder:latest

      - name: Build PDF using make_sofp_pdf.sh
        run: echo TODO
  
      - name: Upload any log files if an error occured
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: |
            ./sofp-src/sofp.log
            ./sofp-src/mispelled_words
        
      - name: Upload built PDF
        uses: actions/upload-artifact@v2
        with:
          name: sofp-${{ github.sha }}.pdf
          path: ./sofp-src/sofp.pdf
          if-no-files-found: error
